---
title: "Pivot_Table_testing"
author: "Jack Sudds"
date: "06/08/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, echo=FALSE, include=FALSE}
##attatch libraries
library(tidyverse)
library(readxl)
library(here)
library(skimr) #install.packages("skimr")
#library(kableExtra) #install.packages("kableExtra")
library(formattable)#install.packages("formattable")
```

```{r importing_data, include=FALSE}
##bring in THE DATA
lobsters <- read_excel(here("data/lobsters2.xlsx"), skip=4)

skimr::skim(lobsters)
```

```{r simple_summaries, include=FALSE}
##create the tables and summarize
lobsters %>%
  group_by(year) %>%
  summarise(count_by_year = n())

lobsters %>%
  group_by(site, year) %>%
  summarise(count_by_siteyear = n())
``` 

```{r complex_summaries, include=FALSE}
##multiple summarised variables
siteyear_summary <- lobsters %>%
  group_by(site, year) %>%
  summarise(count_by_siteyear = n(),
            mean_size_mm = mean(size_mm, na.rm=TRUE),
            sd_size_mm = sd(size_mm, na.rm=TRUE))
```

```{r kabling}
siteyear_summary %>%
  kable()
```

There are `r nrow(lobsters)` total lobsters included in this report

```{r counting_over_kable}
lobsters %>%
  count(site, year)
```

There are `r count(lobsters)` lobsters in this dataset

```{r x_men_chart}
tweaked_lobsters <- lobsters %>%
  mutate(size_m = size_mm / 1000)

#tweaked_lobsters %>%
  #kable()

##subset variables with columns

tweaked_lobsters %>%
  select(date, site, size_m)
```

```{r formattable for nice tables}

#formattable(siteyear_summary) #generates formattable table from dataframe
#formattable(siteyear_summary,
            #align = c ("l","c","c","c","r"),
            #list(`site` = formatter(
             # "span", style = ~ style(color = "grey", font.weight = "bold")),
              #`count_by_siteyear` = color_bar("#2bfe72")))  
  #alter formatting of individual columns and add color bars, can also express the column as a percent with "= percent" 

formattable(siteyear_summary,
            align = c ("l","c","c","c","r"),
            list(`site` = formatter(
              "span", style = ~ style(color = "grey", font.weight = "bold")),
              #`count_by_siteyear` = color_bar("#2bfe72"))) 
              area(col = 3) ~ color_tile("#DeF7E9", "#71CA97")))

```

