---
title: "First_graphing"
author: "Jack Sudds"
date: "06/08/2020"
output: html_document
---
```{r}
##setup of packages
#install.packages("tidyverse")
#install.packages("readxl")
#install.packages("here")
library(tidyverse)
library(readxl)
library(here)

##create code chunk, read file, location from file using here
ca_np <- read_csv(here("data", "ca_np.csv"))
names(ca_np)
summary(ca_np)
```

```{r}
##read excell file
ci_np <- read_excel(here("data", "ci_np.xlsx"))
```

```{r}
##plotting time!
#ggplot2::ggplot(data = ci_np, aes(x = year, y = visitors)) +
  #geom_line()

##turn the graph into a new code chunk!
gg_base <- ggplot2::ggplot(data = ci_np, aes(x = year, y = visitors))

##using code chunk to build graphs ... various
gg_base + 
  geom_point(
    aes(size = year,
        color = visitors),
    alpha = 0.6
  ) +
  geom_line(color = "red") +
  theme_linedraw() +
  labs(
    x = "Year",
    y = "Annual Park Visitors",
    title = "Channel Islands NP Visitors",
    subtitle = "(1963 - 2016)"
  )

gg_base +
  geom_col(aes(fill = visitors)) +
  theme_linedraw() +
  labs(
    x = "Year",
    y = "Annual Park Visitors",
    title = "Channel Islands NP Visitors",
    subtitle = "(1963 - 2016)"
  )
    
gg_base +
  geom_col(fill = "orange",
           color = "purple4") +
  geom_line(color = "green") +
  theme_linedraw() +
  labs(
    x = "Year",
    y = "Annual Park Visitors",
    title = "Channel Islands NP Visitors",
    subtitle = "(1963 - 2016)"
  )

##graphs with multiple series displayed on the same set of axis
ggplot2::ggplot(data = ca_np, aes(x = year, y = visitors, group = park_name)) +
  geom_line()

##storing this multi-series graph
gg_np <- ggplot2::ggplot(data = ca_np, aes(x = year, y = visitors, group = park_name))

##faceting
gg_np +
  geom_line() +
  theme_light() +
    labs(x = "Year", y = "annual visitors") +
    facet_wrap(~ park_name)
ggsave(here("figures", "saving_graphs_is_a_novelty.jpg"), dpi = 180, width = 8, height = 7)
                         
```


