---
title: "Tidying_Up"
author: "Jack Sudds"
date: "06/08/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packaging}
library(tidyverse)
library(here)
library(readxl)
library(janitor)#install.packages("janitor")
```

```{r data_insert}
inverts <- read_excel(here("data", "inverts.xlsx"))
```

```{r pivoting_tables}
inverts_long = tidyr::pivot_longer(data = inverts,
                      cols = '2016':'2018',
                      names_to = "year",
                      values_to = "sp_count")

##converting the "year" column to a numeric value rather than character
#inverts_long <- inverts_long %>%
   #mutate(year = as.numeric(year))

##converting from long to wide
inverts_wide <- inverts_long %>%
  pivot_wider(names_from = common_name,
                values_from = sp_count)
```

```{r janitor_stuffs}
##janitor can be used to clean up stuff (clean_names(), get_dupes(), remove_empty() & adorn_*())

inverts_wide <- inverts_wide %>%
janitor::clean_names()

```

```{r uniting}
##taking multiple columns and turnign them innto a single one
inverts_unite <- inverts_long %>%
  unite(col = "site_year",
        c(site, year),
        sep = "_")

inverts_moyr <- inverts_long %>%
  unite(col = "mo_yr",
        c(month,year),
        sep = "/")

##can also do more than 2 columns

inverts_experimental <- inverts_long %>%
  unite(col = "mo_yr_site",
        c(month, year, site),
        sep = "-")

##seperating 1 column into multiple

inverts_sep <- inverts_unite %>%
  tidyr::separate(site_year, into = c("my_site", "my_year"))

##fixing spelling mistakes - WARNING dumb machine finds strings even in other words

ca_abbr <- inverts %>%
  mutate(
    common_name = 
      str_replace(common_name, 
                  pattern = "california",
                  replacement = "CA")
  )
```

