---
title: "Vlookup_equivalent"
author: "Jack Sudds"
date: "07/08/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packaging}
library(tidyverse)
library(here)
library(readxl)
library(kableExtra)
```

```{r data_in}

fish <- read_csv(here("data", "fish.csv"))
kelp_abur <- read_excel(here("data", "kelp.xlsx"), sheet = "abur")
```

```{r filtering_rows}

fish_garibaldi <- fish %>%
  filter(common_name == "garibaldi")

fish_mohk <- fish %>%
  filter(site == "mohk")

fish_over50 <- fish %>%
  filter(total_count >= 50)

##filtering can be multiple possibilities with OR indicated by |
fish_3sp <- fish %>%
  filter(common_name == "garibaldi" |
           common_name == "blacksmith" |
           common_name == "black surfpech")

##where all in same variable

fish_2sp <- fish %>%
  filter(common_name %in% c("garibaldi", "blacksmith"))

##for AND opperations just use comma or &

fish_gar_2016 <- fish %>%
  filter(common_name == "garibaldi", year == 2016)
```

```{r joining}
##simply putting everything together gaps and all

abur_kelp_fish <- kelp_abur %>%
  full_join(fish, by = c("year", "site"))

```

